// Структура: [Symbol, Name, Group, Period]
export interface ElementData {
    symbol: string;
    name: string;
    group: number;
    period: number;
    block: string;
    color: string;
}

export const PERIODIC: Record<number, ElementData> = {
    1:  { symbol: "H",  name: "Hydrogen", group: 1, period: 1, block: "s", color: "#4dabf7" },
    2:  { symbol: "He", name: "Helium", group: 18, period: 1, block: "p", color: "#ffa94d" },
    3:  { symbol: "Li", name: "Lithium", group: 1, period: 2, block: "s", color: "#4dabf7" },
    4:  { symbol: "Be", name: "Beryllium", group: 2, period: 2, block: "s", color: "#4dabf7" },
    5:  { symbol: "B",  name: "Boron", group: 13, period: 2, block: "p", color: "#ffa94d" },
    6:  { symbol: "C",  name: "Carbon", group: 14, period: 2, block: "p", color: "#ffa94d" },
    7:  { symbol: "N",  name: "Nitrogen", group: 15, period: 2, block: "p", color: "#ffa94d" },
    8:  { symbol: "O",  name: "Oxygen", group: 16, period: 2, block: "p", color: "#ffa94d" },
    9:  { symbol: "F",  name: "Fluorine", group: 17, period: 2, block: "p", color: "#ffa94d" },
    10: { symbol: "Ne", name: "Neon", group: 18, period: 2, block: "p", color: "#ffa94d" },
    11: { symbol: "Na", name: "Sodium", group: 1, period: 3, block: "s", color: "#4dabf7" },
    12: { symbol: "Mg", name: "Magnesium", group: 2, period: 3, block: "s", color: "#4dabf7" },
    13: { symbol: "Al", name: "Aluminium", group: 13, period: 3, block: "p", color: "#ffa94d" },
    14: { symbol: "Si", name: "Silicon", group: 14, period: 3, block: "p", color: "#ffa94d" },
    15: { symbol: "P",  name: "Phosphorus", group: 15, period: 3, block: "p", color: "#ffa94d" },
    16: { symbol: "S",  name: "Sulfur", group: 16, period: 3, block: "p", color: "#ffa94d" },
    17: { symbol: "Cl", name: "Chlorine", group: 17, period: 3, block: "p", color: "#ffa94d" },
    18: { symbol: "Ar", name: "Argon", group: 18, period: 3, block: "p", color: "#ffa94d" },
    19: { symbol: "K",  name: "Potassium", group: 1, period: 4, block: "s", color: "#4dabf7" },
    20: { symbol: "Ca", name: "Calcium", group: 2, period: 4, block: "s", color: "#4dabf7" },
    21: { symbol: "Sc", name: "Scandium", group: 3, period: 4, block: "d", color: "#a9e34b" },
    22: { symbol: "Ti", name: "Titanium", group: 4, period: 4, block: "d", color: "#a9e34b" },
    23: { symbol: "V",  name: "Vanadium", group: 5, period: 4, block: "d", color: "#a9e34b" },
    24: { symbol: "Cr", name: "Chromium", group: 6, period: 4, block: "d", color: "#a9e34b" },
    25: { symbol: "Mn", name: "Manganese", group: 7, period: 4, block: "d", color: "#a9e34b" },
    26: { symbol: "Fe", name: "Iron", group: 8, period: 4, block: "d", color: "#a9e34b" },
    27: { symbol: "Co", name: "Cobalt", group: 9, period: 4, block: "d", color: "#a9e34b" },
    28: { symbol: "Ni", name: "Nickel", group: 10, period: 4, block: "d", color: "#a9e34b" },
    29: { symbol: "Cu", name: "Copper", group: 11, period: 4, block: "d", color: "#a9e34b" },
    30: { symbol: "Zn", name: "Zinc", group: 12, period: 4, block: "d", color: "#a9e34b" },
    31: { symbol: "Ga", name: "Gallium", group: 13, period: 4, block: "p", color: "#ffa94d" },
    32: { symbol: "Ge", name: "Germanium", group: 14, period: 4, block: "p", color: "#ffa94d" },
    33: { symbol: "As", name: "Arsenic", group: 15, period: 4, block: "p", color: "#ffa94d" },
    34: { symbol: "Se", name: "Selenium", group: 16, period: 4, block: "p", color: "#ffa94d" },
    35: { symbol: "Br", name: "Bromine", group: 17, period: 4, block: "p", color: "#ffa94d" },
    36: { symbol: "Kr", name: "Krypton", group: 18, period: 4, block: "p", color: "#ffa94d" },
    37: { symbol: "Rb", name: "Rubidium", group: 1, period: 5, block: "s", color: "#4dabf7" },
    38: { symbol: "Sr", name: "Strontium", group: 2, period: 5, block: "s", color: "#4dabf7" },
    39: { symbol: "Y",  name: "Yttrium", group: 3, period: 5, block: "d", color: "#a9e34b" },
    40: { symbol: "Zr", name: "Zirconium", group: 4, period: 5, block: "d", color: "#a9e34b" },
    41: { symbol: "Nb", name: "Niobium", group: 5, period: 5, block: "d", color: "#a9e34b" },
    42: { symbol: "Mo", name: "Molybdenum", group: 6, period: 5, block: "d", color: "#a9e34b" },
    43: { symbol: "Tc", name: "Technetium", group: 7, period: 5, block: "d", color: "#a9e34b" },
    44: { symbol: "Ru", name: "Ruthenium", group: 8, period: 5, block: "d", color: "#a9e34b" },
    45: { symbol: "Rh", name: "Rhodium", group: 9, period: 5, block: "d", color: "#a9e34b" },
    46: { symbol: "Pd", name: "Palladium", group: 10, period: 5, block: "d", color: "#a9e34b" },
    47: { symbol: "Ag", name: "Silver", group: 11, period: 5, block: "d", color: "#a9e34b" },
    48: { symbol: "Cd", name: "Cadmium", group: 12, period: 5, block: "d", color: "#a9e34b" },
    49: { symbol: "In", name: "Indium", group: 13, period: 5, block: "p", color: "#ffa94d" },
    50: { symbol: "Sn", name: "Tin", group: 14, period: 5, block: "p", color: "#ffa94d" },
    51: { symbol: "Sb", name: "Antimony", group: 15, period: 5, block: "p", color: "#ffa94d" },
    52: { symbol: "Te", name: "Tellurium", group: 16, period: 5, block: "p", color: "#ffa94d" },
    53: { symbol: "I",  name: "Iodine", group: 17, period: 5, block: "p", color: "#ffa94d" },
    54: { symbol: "Xe", name: "Xenon", group: 18, period: 5, block: "p", color: "#ffa94d" },
    55: { symbol: "Cs", name: "Cesium", group: 1, period: 6, block: "s", color: "#4dabf7" },
    56: { symbol: "Ba", name: "Barium", group: 2, period: 6, block: "s", color: "#4dabf7" },
    57: { symbol: "La", name: "Lanthanum", group: 3, period: 9, block: "f", color: "#da77f2" }, // Lanth series start
    72: { symbol: "Hf", name: "Hafnium", group: 4, period: 6, block: "d", color: "#a9e34b" },
    73: { symbol: "Ta", name: "Tantalum", group: 5, period: 6, block: "d", color: "#a9e34b" },
    74: { symbol: "W",  name: "Tungsten", group: 6, period: 6, block: "d", color: "#a9e34b" },
    75: { symbol: "Re", name: "Rhenium", group: 7, period: 6, block: "d", color: "#a9e34b" },
    76: { symbol: "Os", name: "Osmium", group: 8, period: 6, block: "d", color: "#a9e34b" },
    77: { symbol: "Ir", name: "Iridium", group: 9, period: 6, block: "d", color: "#a9e34b" },
    78: { symbol: "Pt", name: "Platinum", group: 10, period: 6, block: "d", color: "#a9e34b" },
    79: { symbol: "Au", name: "Gold", group: 11, period: 6, block: "d", color: "#a9e34b" },
    80: { symbol: "Hg", name: "Mercury", group: 12, period: 6, block: "d", color: "#a9e34b" },
    81: { symbol: "Tl", name: "Thallium", group: 13, period: 6, block: "p", color: "#ffa94d" },
    82: { symbol: "Pb", name: "Lead", group: 14, period: 6, block: "p", color: "#ffa94d" },
    83: { symbol: "Bi", name: "Bismuth", group: 15, period: 6, block: "p", color: "#ffa94d" },
    84: { symbol: "Po", name: "Polonium", group: 16, period: 6, block: "p", color: "#ffa94d" },
    85: { symbol: "At", name: "Astatine", group: 17, period: 6, block: "p", color: "#ffa94d" },
    86: { symbol: "Rn", name: "Radon", group: 18, period: 6, block: "p", color: "#ffa94d" },
    87: { symbol: "Fr", name: "Francium", group: 1, period: 7, block: "s", color: "#4dabf7" },
    88: { symbol: "Ra", name: "Radium", group: 2, period: 7, block: "s", color: "#4dabf7" },
    89: { symbol: "Ac", name: "Actinium", group: 3, period: 10, block: "f", color: "#da77f2" }, // Actin series start
    104: { symbol: "Rf", name: "Rutherfordium", group: 4, period: 7, block: "d", color: "#a9e34b" },
    105: { symbol: "Db", name: "Dubnium", group: 5, period: 7, block: "d", color: "#a9e34b" },
    106: { symbol: "Sg", name: "Seaborgium", group: 6, period: 7, block: "d", color: "#a9e34b" },
    107: { symbol: "Bh", name: "Bohrium", group: 7, period: 7, block: "d", color: "#a9e34b" },
    108: { symbol: "Hs", name: "Hassium", group: 8, period: 7, block: "d", color: "#a9e34b" },
    109: { symbol: "Mt", name: "Meitnerium", group: 9, period: 7, block: "d", color: "#a9e34b" },
    110: { symbol: "Ds", name: "Darmstadtium", group: 10, period: 7, block: "d", color: "#a9e34b" },
    111: { symbol: "Rg", name: "Roentgenium", group: 11, period: 7, block: "d", color: "#a9e34b" },
    112: { symbol: "Cn", name: "Copernicium", group: 12, period: 7, block: "d", color: "#a9e34b" },
    113: { symbol: "Nh", name: "Nihonium", group: 13, period: 7, block: "p", color: "#ffa94d" },
    114: { symbol: "Fl", name: "Flerovium", group: 14, period: 7, block: "p", color: "#ffa94d" },
    115: { symbol: "Mc", name: "Moscovium", group: 15, period: 7, block: "p", color: "#ffa94d" },
    116: { symbol: "Lv", name: "Livermorium", group: 16, period: 7, block: "p", color: "#ffa94d" },
    117: { symbol: "Ts", name: "Tennessine", group: 17, period: 7, block: "p", color: "#ffa94d" },
    118: { symbol: "Og", name: "Oganesson", group: 18, period: 7, block: "p", color: "#ffa94d" },
    // Lanthanides (58-71)
    58: { symbol: "Ce", name: "Cerium", group: 4, period: 9, block: "f", color: "#da77f2" },
    59: { symbol: "Pr", name: "Praseodymium", group: 5, period: 9, block: "f", color: "#da77f2" },
    60: { symbol: "Nd", name: "Neodymium", group: 6, period: 9, block: "f", color: "#da77f2" },
    61: { symbol: "Pm", name: "Promethium", group: 7, period: 9, block: "f", color: "#da77f2" },
    62: { symbol: "Sm", name: "Samarium", group: 8, period: 9, block: "f", color: "#da77f2" },
    63: { symbol: "Eu", name: "Europium", group: 9, period: 9, block: "f", color: "#da77f2" },
    64: { symbol: "Gd", name: "Gadolinium", group: 10, period: 9, block: "f", color: "#da77f2" },
    65: { symbol: "Tb", name: "Terbium", group: 11, period: 9, block: "f", color: "#da77f2" },
    66: { symbol: "Dy", name: "Dysprosium", group: 12, period: 9, block: "f", color: "#da77f2" },
    67: { symbol: "Ho", name: "Holmium", group: 13, period: 9, block: "f", color: "#da77f2" },
    68: { symbol: "Er", name: "Erbium", group: 14, period: 9, block: "f", color: "#da77f2" },
    69: { symbol: "Tm", name: "Thulium", group: 15, period: 9, block: "f", color: "#da77f2" },
    70: { symbol: "Yb", name: "Ytterbium", group: 16, period: 9, block: "f", color: "#da77f2" },
    71: { symbol: "Lu", name: "Lutetium", group: 17, period: 9, block: "f", color: "#da77f2" },
    // Actinides (90-103)
    90: { symbol: "Th", name: "Thorium", group: 4, period: 10, block: "f", color: "#da77f2" },
    91: { symbol: "Pa", name: "Protactinium", group: 5, period: 10, block: "f", color: "#da77f2" },
    92: { symbol: "U", name: "Uranium", group: 6, period: 10, block: "f", color: "#da77f2" },
    93: { symbol: "Np", name: "Neptunium", group: 7, period: 10, block: "f", color: "#da77f2" },
    94: { symbol: "Pu", name: "Plutonium", group: 8, period: 10, block: "f", color: "#da77f2" },
    95: { symbol: "Am", name: "Americium", group: 9, period: 10, block: "f", color: "#da77f2" },
    96: { symbol: "Cm", name: "Curium", group: 10, period: 10, block: "f", color: "#da77f2" },
    97: { symbol: "Bk", name: "Berkelium", group: 11, period: 10, block: "f", color: "#da77f2" },
    98: { symbol: "Cf", name: "Californium", group: 12, period: 10, block: "f", color: "#da77f2" },
    99: { symbol: "Es", name: "Einsteinium", group: 13, period: 10, block: "f", color: "#da77f2" },
    100: { symbol: "Fm", name: "Fermium", group: 14, period: 10, block: "f", color: "#da77f2" },
    101: { symbol: "Md", name: "Mendelevium", group: 15, period: 10, block: "f", color: "#da77f2" },
    102: { symbol: "No", name: "Nobelium", group: 16, period: 10, block: "f", color: "#da77f2" },
    103: { symbol: "Lr", name: "Lawrencium", group: 17, period: 10, block: "f", color: "#da77f2" },
};

// Orbital filling order (Aufbau Principle)
export const AUFBAU: [number, number, string, number][] = [
    // [n, l, label, capacity]
    [1, 0, '1s', 2],
    [2, 0, '2s', 2],
    [2, 1, '2p', 6],
    [3, 0, '3s', 2],
    [3, 1, '3p', 6],
    [4, 0, '4s', 2],
    [3, 2, '3d', 10],
    [4, 1, '4p', 6],
    [5, 0, '5s', 2],
    [4, 2, '4d', 10],
    [5, 1, '5p', 6],
    [6, 0, '6s', 2],
    [4, 3, '4f', 14],
    [5, 2, '5d', 10],
    [6, 1, '6p', 6],
    [7, 0, '7s', 2],
    [5, 3, '5f', 14],
    [6, 2, '6d', 10],
    [7, 1, '7p', 6],
];